package co.edu.uniquindio.poo;

public enum Especializacion {
    DERMATOLOGIA, OFTALMOLOFIA, CARDIOLOGIA, NEUROLOGIA, ONCOLOGIA, ORTOPEDIA, ENDOCRINOLOGIA, GASTROENTEROLOGIA,
    MEDICINA_INTERNA;
}
